#pragma once
const int SCREEN_INDEX_NO_INDEX = -1;
const int SCREEN_INDEX_MENU = 0;
const int SCREEN_INDEX_GAMEPLAY = 1;
const int SCREEN_INDEX_LEVEL_EDITOR_SELECTOR = 2;
const int SCREEN_INDEX_LEVEL_EDITOR_NEW = 3;
const int SCREEN_INDEX_LEVEL_EDITOR = 4;
const int SCREEN_INDEX_CREDITS = 5; //Maybe mover
