#pragma once
const int SCREEN_INDEX_NO_INDEX = -1;
const int SCREEN_INDEX_CREDITS = 0; //Maybe mover
const int SCREEN_INDEX_MENU = 1;
const int SCREEN_INDEX_GAMEPLAY = 2;
const int SCREEN_INDEX_LEVEL_EDITOR_SELECTOR = 3;
const int SCREEN_INDEX_LEVEL_EDITOR_NEW = 4;
const int SCREEN_INDEX_LEVEL_EDITOR = 5;
